### ISSUE TITLE
don't include min/max for common number types

### ISSUE THREAD

**Issue by buchanae** [devongovett/protobuf-jsonschema#6]
```
      start:
        type: integer
        minimum: -9007199254740991
        maximum: 9007199254740991
```

Similar output occurs for int32. These should be omitted.
